/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAdminAgentesRouteImport } from './routes/_authenticated/admin/agentes'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedConfigIaLocalRouteImport } from './routes/_authenticated/config/ia-local'
import { Route as AuthenticatedConfigPreferenciasRouteImport } from './routes/_authenticated/config/preferencias'
import { Route as AuthenticatedConfigPrivacidadeRouteImport } from './routes/_authenticated/config/privacidade'
import { Route as AuthenticatedConfigVozDeMarcaRouteImport } from './routes/_authenticated/config/voz-de-marca'
import { Route as AuthenticatedAppCChatIdRouteImport } from './routes/_authenticated/app/c.$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAgentesRoute =
  AuthenticatedAdminAgentesRouteImport.update({
    id: '/admin/agentes',
    path: '/admin/agentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigIaLocalRoute =
  AuthenticatedConfigIaLocalRouteImport.update({
    id: '/config/ia-local',
    path: '/config/ia-local',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigPreferenciasRoute =
  AuthenticatedConfigPreferenciasRouteImport.update({
    id: '/config/preferencias',
    path: '/config/preferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigPrivacidadeRoute =
  AuthenticatedConfigPrivacidadeRouteImport.update({
    id: '/config/privacidade',
    path: '/config/privacidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigVozDeMarcaRoute =
  AuthenticatedConfigVozDeMarcaRouteImport.update({
    id: '/config/voz-de-marca',
    path: '/config/voz-de-marca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCChatIdRoute = AuthenticatedAppCChatIdRouteImport.update({
  id: '/app/c/$chatId',
  path: '/app/c/$chatId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/agentes': typeof AuthenticatedAdminAgentesRoute
  '/config/ia-local': typeof AuthenticatedConfigIaLocalRoute
  '/config/preferencias': typeof AuthenticatedConfigPreferenciasRoute
  '/config/privacidade': typeof AuthenticatedConfigPrivacidadeRoute
  '/config/voz-de-marca': typeof AuthenticatedConfigVozDeMarcaRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/c/$chatId': typeof AuthenticatedAppCChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/agentes': typeof AuthenticatedAdminAgentesRoute
  '/config/ia-local': typeof AuthenticatedConfigIaLocalRoute
  '/config/preferencias': typeof AuthenticatedConfigPreferenciasRoute
  '/config/privacidade': typeof AuthenticatedConfigPrivacidadeRoute
  '/config/voz-de-marca': typeof AuthenticatedConfigVozDeMarcaRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/c/$chatId': typeof AuthenticatedAppCChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/admin/agentes': typeof AuthenticatedAdminAgentesRoute
  '/_authenticated/config/ia-local': typeof AuthenticatedConfigIaLocalRoute
  '/_authenticated/config/preferencias': typeof AuthenticatedConfigPreferenciasRoute
  '/_authenticated/config/privacidade': typeof AuthenticatedConfigPrivacidadeRoute
  '/_authenticated/config/voz-de-marca': typeof AuthenticatedConfigVozDeMarcaRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/c/$chatId': typeof AuthenticatedAppCChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin/agentes'
    | '/config/ia-local'
    | '/config/preferencias'
    | '/config/privacidade'
    | '/config/voz-de-marca'
    | '/app/'
    | '/app/c/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin/agentes'
    | '/config/ia-local'
    | '/config/preferencias'
    | '/config/privacidade'
    | '/config/voz-de-marca'
    | '/app'
    | '/app/c/$chatId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/onboarding'
    | '/_authenticated/admin/agentes'
    | '/_authenticated/config/ia-local'
    | '/_authenticated/config/preferencias'
    | '/_authenticated/config/privacidade'
    | '/_authenticated/config/voz-de-marca'
    | '/_authenticated/app/'
    | '/_authenticated/app/c/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agentes': {
      id: '/_authenticated/admin/agentes'
      path: '/admin/agentes'
      fullPath: '/admin/agentes'
      preLoaderRoute: typeof AuthenticatedAdminAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/ia-local': {
      id: '/_authenticated/config/ia-local'
      path: '/config/ia-local'
      fullPath: '/config/ia-local'
      preLoaderRoute: typeof AuthenticatedConfigIaLocalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/preferencias': {
      id: '/_authenticated/config/preferencias'
      path: '/config/preferencias'
      fullPath: '/config/preferencias'
      preLoaderRoute: typeof AuthenticatedConfigPreferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/privacidade': {
      id: '/_authenticated/config/privacidade'
      path: '/config/privacidade'
      fullPath: '/config/privacidade'
      preLoaderRoute: typeof AuthenticatedConfigPrivacidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/voz-de-marca': {
      id: '/_authenticated/config/voz-de-marca'
      path: '/config/voz-de-marca'
      fullPath: '/config/voz-de-marca'
      preLoaderRoute: typeof AuthenticatedConfigVozDeMarcaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/c/$chatId': {
      id: '/_authenticated/app/c/$chatId'
      path: '/app/c/$chatId'
      fullPath: '/app/c/$chatId'
      preLoaderRoute: typeof AuthenticatedAppCChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAdminAgentesRoute: typeof AuthenticatedAdminAgentesRoute
  AuthenticatedConfigIaLocalRoute: typeof AuthenticatedConfigIaLocalRoute
  AuthenticatedConfigPreferenciasRoute: typeof AuthenticatedConfigPreferenciasRoute
  AuthenticatedConfigPrivacidadeRoute: typeof AuthenticatedConfigPrivacidadeRoute
  AuthenticatedConfigVozDeMarcaRoute: typeof AuthenticatedConfigVozDeMarcaRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCChatIdRoute: typeof AuthenticatedAppCChatIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAdminAgentesRoute: AuthenticatedAdminAgentesRoute,
  AuthenticatedConfigIaLocalRoute: AuthenticatedConfigIaLocalRoute,
  AuthenticatedConfigPreferenciasRoute: AuthenticatedConfigPreferenciasRoute,
  AuthenticatedConfigPrivacidadeRoute: AuthenticatedConfigPrivacidadeRoute,
  AuthenticatedConfigVozDeMarcaRoute: AuthenticatedConfigVozDeMarcaRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCChatIdRoute: AuthenticatedAppCChatIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
